### PR TITLE
Aggressive cows

### PR DESCRIPTION
**Pull request by j-shreya**
Aggressive cows problem in java

Issue no: #1903 
Fixes #

#### Checklist:
- [X] 4 space indentation.
- [X] Coding conventions are followed.
- [X] Input is taken dynamically.
- [X] Sample Input / Output is added at the end of file.
- [X] Logic Documentation (Comments).
- [X] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- JAVA
- 

#### Files Added:
- Aggressive_Cows.java
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by raghav-dalmia** [comment]
Your PR shows two file changes, remove the irrelevant one. Also squash all the commits.

**Comment by jainaman224** [comment]
@j-shreya Are you working on it?

**Comment by j-shreya** [comment]
yes I am working on it. I have to do domw changes requested by one of the
mentors

**Comment by j-shreya** [comment]
@jainaman224 I am working on it.

**Pull request closed without merging**
