### PR TITLE
Kadane Algorithm 

### LINKED ISSUE #2247: Kadane Algorithm
- [x] C
- [x] C++
- [x] C#
- [x] CoffeeScript
- [x] Dart - @heisastark
- [x] Go - @kushagra-anand
- [x] Java
- [x] JS
- [ ] Kotlin - @yuktta
- [ ] Php - @sukritishah15
- [x] Python
- [ ] Readme - @pragyajaiswa05l
- [x] Ruby
- [ ] Rust - @ujjwaltiwari13
- [ ] TypeScript

### PR DESCRIPTION
**Pull request by kushagra-anand**
Fixes #2247

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Kadane Algorithm in GO

#### Languages Used:
- GO
- 

#### Files Added:
- Kadane_Algorithm.go 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by MastersAbh** [comment]
@kushagra-anand Please squash your commits, I will merge

**Comment by raghav-dalmia** [comment]
@kushagra-anand are you working on it?

**Comment by kushagra-anand** [comment]
Yes. Will do it today. Sorry for the delay

**Comment by MastersAbh** [comment]
@kushagra-anand Are you still working on this ? We will close the PR in case we dont hear back

**Comment by kushagra-anand** [comment]
I am really sorry for the trouble the thing is I am locked out of my GitHub
account and unable to access it. I tried changing the password but it's not
happening.

**Comment by MastersAbh** [comment]
@kushagra-anand please try to set latest password in web credentials if you have windows laptop and then try to access git. Closing this for now. Try to create a new PR if the problem persists. Else, reach out to us on Slack.

**Comment by MastersAbh** [comment]
@kushagra-anand I will merge this PR as only squashing was left. Try to get back to your account by setting latest password in web-credentials in your PC.

**Pull request merged**
