### PR TITLE
Kmp algo

### PR DESCRIPTION
**Pull request by urbashi123**
Fixes #2602 

#### Checklist:
- [ ] 4 space indentation.
- [ ] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [ ] Sample Input / Output is added at the end of file.
- [ ] Logic Documentation (Comments).
- [ ] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!
@jainaman224

### CODE REVIEW

**Comment by asha15** [comment]
please complete the PR template properly

**Comment by asha15** [comment]
You have given the PR ID

could you please remove the extra file from the branch, complete the PR template properly and send a PR again ?

**Comment by urbashi123** [comment]
I wasn't able to understand this? Can you explain please

**Comment by asha15** [comment]
In the PR template you have given the PR ID. not the issue ID (next to **Fixes**)

your PR has many files. please create a PR with only the relevant file. Hope you understand

**Pull request closed without merging**
