### PR TITLE
added assignment problem in C

### PR DESCRIPTION
**Pull request by sagnik-chatterjee**
Fixes #

#### Checklist:
- [ ] 4 space indentation.
- [ ] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [ ] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added assignment problem in C implementation 
- 

#### Languages Used:
- C
- 

#### Files Added:
- ~/assignment_problem/assignment.c
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please complete all the checklist

**Comment by SakshiShreya** [comment]
Are you working on this?

**Comment by sagnik-chatterjee** [comment]
@SakshiShreya  you can take it up ?? I guess i have not done dynamic i/o.

**Comment by jainaman224** [comment]
@sagnik-chatterjee Will you work on it? Or should we close this PR.

**Pull request closed without merging**
