### PR TITLE
added disjoint sets in c++

### PR DESCRIPTION
**Pull request by mr-pandey**
Implementation of Disjoint Sets using path compression to find connected components of a graph. Also used as a sub-algorithm of some famous algorithms

### CODE REVIEW

**Comment by mr-pandey** [comment]
> Implementation of Disjoint Sets using path compression to find connected components of a graph. Also used as a sub-algorithm of some famous algorithms

I'm participating in GSSoC

**Comment by jainaman224** [comment]
Please refer the issue you were assigned.

**Comment by gupta2140** [comment]
Very nicely implemented!

**Comment by mr-pandey** [comment]
Thanks a lot @gupta2140  
I'm new to GitHub and open source as well.
I really appreciate your support @jainaman224  @rishabhgarg25699  @gupta2140

**Comment by jainaman224** [comment]
Duplicate PR #637

**Pull request closed without merging**
