### PR TITLE
Added Length of Longest Bitonic Subsequence in Python

### LINKED ISSUE #816: Length of Longest Bitonic Subsequence for a given array in C/C++, Java, Python, PHP and JavaScript
Problem Statement:
Given an array arr[0 … n-1] containing n positive integers, a subsequence of arr[ ] is called Bitonic if it is first increasing first and then decreasing. 
For example:
  Input arr[ ] = {1, 11, 2, 10, 4, 5, 2, 1}
  Output: 6 
A Longest Bitonic Subsequence of length 6 is {1, 2, 10, 4, 2, 1}.

### PR DESCRIPTION
**Pull request by ayanujju**
Fixes # 816
#### Files Added:
- Length_of_Longest_Bitonic_Subsequence.py

### CODE REVIEW

**Comment by somya-kapoor** [comment]
Please fix the PR title as you submitting it in python.
And your code seems to be copied from GFG https://www.geeksforgeeks.org/longest-bitonic-subsequence-dp-15/. Please learn the algorithm and then implement it yourself.
@jainaman224

**Comment by ayanujju** [comment]
After trying too much, I was not able to solve the question completely. So, I have taken help from GFG and understand the solution and C/P this. I apologized for this and making sure you that I'll submit my own solution next time on wards. Thanks for your action.

**Comment by MastersAbh** [comment]
@ayanujju The issue is unassigned right now. Please go at #816 and request @jainaman224  to assign it to you before you can work on this again.

**Comment by MastersAbh** [comment]
@ayanujju You can still make changes in your code and commit to this PR.

**Comment by ayanujju** [comment]
Sure, will commit my code within two days.

**Pull request closed without merging**
