### PR TITLE
Created A* Algorithm in C++ #1005

### PR DESCRIPTION
**Pull request by shahkv95**
**Issue index: #1005**
It is basically a search algorithm to find the shortest path from one point to another point in a given grid along with certain given constraints. These constraints are obstacles/inaccessible blocks in a path in a real life applications - such as finding shortest path in a map.

Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by marwahmanbir** [comment]
PR template also incomplete.

**Comment by jainaman224** [comment]
@marwahmanbir Please do the needful.

**Comment by MastersAbh** [comment]
@rishabhgarg25699 @marwahmanbir you can close the PR.

**Comment by marwahmanbir** [comment]
@shahkv95 are you working on this? A little over a day left for GSSoC to conclude.

**Comment by MastersAbh** [comment]
@rishabhgarg25699 you can close it.

**Pull request closed without merging**
