### PR TITLE
Added Aho Corasick in Java

### LINKED ISSUE #1760: Aho-Corasick Algorithm
I'm proficient in Data structures and algorithms. I would love to contribute it as a part of GSSoc '20. Please assign it to me!

### PR DESCRIPTION
**Pull request by topcoder69**
Fixes #1760 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- Java
- 

#### Files Added:
- AhoCorasick.java

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by jainaman224** [comment]
@topcoder69 Please read about git branching.

**Comment by jainaman224** [comment]
You need to work on separate branches and create separate PR for different issues.

**Comment by jainaman224** [comment]
You can also ask for help on slack channel name `git_github`.

**Comment by topcoder69** [comment]
> You need to work on separate branches and create separate PR for different issues.

Okay thanks! Will create a new PR for Arithmetic Progression, but is Aho-Corasick in Java merged? It's been more than 60 hrs :(

**Pull request closed without merging**
