### PR TITLE
Implemented Leap Year code in JavaScript Issue#1867

### LINKED ISSUE #1867: Implement Leap Year code in JavaScript
Please assign me this issue @SakshiShreya @singh-shreya6 @jainaman224 @asha15 @somya-kapoor  @Vaibhavraj10 @raghav-dalmia

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fixes #1867 
Implemented Leap Year Code in JavaScript
2 files added

### CODE REVIEW

**Comment by asha15** [comment]
please complete the PR template 
remove unnecessary files

**Comment by SakshiShreya** [comment]
Please use the PR template while raising a PR. You have to correct it first so that we can review properly.

**Comment by shreyakapoor08** [comment]
> Please use the PR template while raising a PR. You have to correct it first so that we can review properly.

I was not able to access this branch due to some error , hence i made a separate PR from another branch
https://github.com/jainaman224/Algo_Ds_Notes/pull/2254

kindly check this link. I have corrected the PR template and removed the unnecessary files.

**Comment by MastersAbh** [comment]
@shreyakapoor08 As per your confirmation, #2254 is raised to reference the same issue. So, closing this PR

**Pull request closed without merging**
