### PR TITLE
Rohit singh rathaur

### PR DESCRIPTION
**Pull request by TeAmP0is0N**
Fixes #

#### Checklist:
- [X] 4 space indentation.
- [X] Coding conventions are followed.
- [X] Input is taken dynamically.
- [X] Sample Input / Output is added at the end of file.
- [X] Logic Documentation (Comments).
- [X] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by TeAmP0is0N** [comment]
It is the Warshall’s Algorithm to find Transitive Closure. Soon, I will add the code for this algo.

**Comment by SakshiShreya** [comment]
Are you working on this?

**Comment by TeAmP0is0N** [comment]
Yes, I am working on this. But who will review it?

**Comment by TeAmP0is0N** [comment]
@SakshiShreya Please review it now. I have completed it.

**Comment by shubhammantri1** [comment]
Input is not taken dynamically. Please change this.

**Comment by TeAmP0is0N** [comment]
@shubhammantri1 Done!

**Comment by TeAmP0is0N** [comment]
@SakshiShreya I have completed it. Please review now.

**Comment by jainaman224** [comment]
@TeAmP0is0N Please tell us the issue number.

**Comment by jainaman224** [comment]
There is no issue assigned for this. Therefore closing it. Please get issue assigned first.

**Pull request closed without merging**
