### PR TITLE
modifying the Bubble_sort function

### PR DESCRIPTION
**Pull request by souravs17031999**
proposing the change in Bubble_sort function by introducing the flag variable so that it keeps check on if at any time the array is sorted then break out of loop which means less computations and in python it is more useful as python is already slower and takes a lot of time for execution.

### CODE REVIEW

**Comment by jainaman224** [comment]
Optimisation is modified bubble sort.

**Comment by souravs17031999** [comment]
I think that's what it is doing .

**Comment by jainaman224** [comment]
I mean to say, people will get confused as your solution is modified bubble sort not original one. Like there are optimised version of merge sort as well. Change folder to modified bubble sort.

**Comment by jainaman224** [comment]
@souravs17031999 Are you still working on it?

**Comment by souravs17031999** [comment]
Nope.
I think it has been resolved and merged.

**Comment by jainaman224** [comment]
Ok. So, can I close this PR?

**Comment by souravs17031999** [comment]
Yes

**Pull request closed without merging**
