### PR TITLE
Fixes #793: exponential search added

### LINKED ISSUE #793: Exponential Search in java, python, javascript and C#
I wish to implement exponential search in above languages.

### PR DESCRIPTION
**Pull request by KanchanThareja**
I have implemented exponential search in java, javascript, python and c# which fixes issue #793 .

### CODE REVIEW

**Comment by jainaman224** [comment]
I think there was a particular format PR description. Please use it.

**Comment by KanchanThareja** [comment]
Fixes #793 

**Changes proposed in this PR:**
* Implementation of exponential search in java, javascript, python, c#


**Languages Used:**
* Java
* Python
* JavaScript
* C#


**Files added:**
* Exponential_Search.py
* Exponential_Search.java
* Exponential_Search.js
* Exponential_Search.cs

**Comment by jainaman224** [comment]
- [ ] 4 space indentation.
- [ ] Coding conventions are followed.
- [ ] Sample Input / Output.
- [ ] Logic Documentation (Comments).
- [ ] File names are correct.

Please fill them as well.

**Comment by jainaman224** [comment]
You will figure out some issues yourself.

**Pull request merged**
