### PR TITLE
Travelling Salesman Problem using Genetic Algorithm

### LINKED ISSUE #1975: Implementation of various Greedy and Optimal Algorithms
This repo also requires a section of greedy algorithms.

### PR DESCRIPTION
**Pull request by Ratna04priya**
Fixes  #1975

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added travelling salesman problem (TSP) using genetic algorithm (GA)
- Added image assets used in main file

#### Languages Used:
- Python3
- Jupyter Notebook (PLatform used)

#### Files Added:
- TSP_GA.ipynb
- image assets - tsp.png , ga.png

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please include you issue number next to 

> Fixes #

**Comment by Ratna04priya** [comment]
Done, Can you please have a look.

**Comment by asha15** [comment]
your file is not available. can you correct the issue

**Comment by jainaman224** [comment]
@Ratna04priya It looks like your code is incorrect and it would be easier for you to create a fresh PR. So, closing this one.

**Pull request closed without merging**
