### PR TITLE
Pull Request under work

### PR DESCRIPTION
**Pull request by AkshitAggarwal**
Fixes # 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:

- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
-

### CODE REVIEW

**Comment by marwahmanbir** [comment]
@AkshitAggarwal mention the issue that this PR fixes and complete rest of the PR template above.

**Comment by somya-kapoor** [comment]
@AkshitAggarwal Also add appropriate comments to explain your logic.

**Comment by jainaman224** [comment]
@AkshitAggarwal Are you working on it?

**Comment by AkshitAggarwal** [comment]
Yes, I'm sorry for the delay. It's due to my End Sem exams. I will finish and upload the code with proper comments, file_name, description in the coming two days.

**Comment by jainaman224** [comment]
No issues, just keeping track.

**Comment by MastersAbh** [comment]
@AkshitAggarwal  Still working on it ?

**Comment by AkshitAggarwal** [comment]
I'm really sorry my exams are going on, I'm not able spare time for this.

**Comment by MastersAbh** [comment]
It is okay. Will you be completing this after the exams ?

**Comment by AkshitAggarwal** [comment]
Yes yes, I will complete all the tasks assigned to me after exams.

**Comment by MastersAbh** [comment]
Hi @AkshitAggarwal , 
still working on it ?

**Comment by MastersAbh** [comment]
@rishabhgarg25699 @jainaman224 you can close this PR due to inactivity.

**Comment by AkshitAggarwal** [comment]
I'm confused on what I was working on, also I think someone completed the task. I'll re-open the pull request with another task. Sorry for the delay.

**Pull request closed without merging**
