### PR TITLE
Added the README.md for the haversine formula

### LINKED ISSUE #1056: Adding README.md file for Haversine formula with example in Java
Haversine formula is used to find the distance between two points on a sphere. I would like to create a readme file containing example in Java for the same.

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixes #1056 

#### Checklist:
- [X] 4 space indentation.
- [X] Coding conventions are followed.
- [X] Sample Input / Output.
- [X] Logic Documentation (Comments).
- [X] File names are correct.

#### Languages Used:
- Java for example

#### Files Added:
- haversine/README.md file

### CODE REVIEW

**Comment by ShivangiSingh17** [comment]
@marwahmanbir can you please review the PR now, I made the suggested changes.

**Comment by ShivangiSingh17** [comment]
@ kanchan thareja what type of images could be inserted here, I didn't get you, can you please guide me?

**Comment by KanchanThareja** [comment]
@ShivangiSingh17 images are a great visual representation of what you want to convey. you can have a look at other already existing readme files. Its not necessary to do so but if you can do it it will be great.
Images and gif should support the algorithm you are describing here. For further queries you can connect with us on slack.

**Comment by jainaman224** [comment]
Please create a file for java code and add that there.

**Comment by MastersAbh** [comment]
Hi @ShivangiSingh17 ,
still working on it ?

**Comment by ShivangiSingh17** [comment]
Yes

**Comment by jainaman224** [comment]
@ShivangiSingh17 Please complete this PR as soon as possible.

**Pull request closed without merging**
