### PR TITLE
Added codes of 1-D_Array in RUBY

### PR DESCRIPTION
**Pull request by nikipr1999**
Fixes # 1826

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Finding frequency of an element in an array
- Max and next max number in array
- Mean Variance and standard deviation
- Merge two sorted arrays

#### Languages Used:
- Ruby

#### Files Added:
- 1-D_Array/Ruby/Frequency_Of_a_element.rb
- 1-D_Array/Ruby/Max_And_Next_Max_Number.rb
- 1-D_Array/Ruby/Standard_Deviation_Mean_Variance.rb
-  1-D_Array/Ruby/Merge_Two_Sorted_Array.rb

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by SakshiShreya** [comment]
Please complete the PR template.

**Comment by jainaman224** [comment]
There is no activity, so please have a look.

**Comment by nikipr1999** [comment]
Please check if its correct.

**Comment by somya-kapoor** [comment]
Please squash the commits.

**Pull request closed without merging**
