### PR TITLE
added palindromic_string program in C/C++

### PR DESCRIPTION
**Pull request by MdAkdas**
Fixes issue No.  #1706

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- New Programs
- 

#### Languages Used:
- C
- C++

#### Files Added:
-Palindromic_string/is_string_palindromic.c
-Palindromic_string/is_string_palindromic.cpp

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by raghav-dalmia** [comment]
Also squash all the commits

**Comment by MdAkdas** [comment]
@raghav-dalmia  please check.

**Comment by raghav-dalmia** [comment]
Squash commits.

**Comment by somya-kapoor** [comment]
There are four other files that are related to this pr. Please delete that files.

**Comment by jainaman224** [comment]
Squash your commits
They are way too many.

**Comment by MdAkdas** [comment]
I've messed up in squashing the commits. that's why i'm making a fresh PR.
please review.
https://github.com/jainaman224/Algo_Ds_Notes/pull/2356

**Pull request closed without merging**
