### PR TITLE
Cycle sort in JS. Closes #1699

### LINKED ISSUE #1699: Add Cycle sort in JavaScript.
@raghav-dalmia I want to implement Cycle Sort in JS (GSSoC' 20)

### PR DESCRIPTION
**Pull request by JanaSabuj**
Fixes #1699 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added Cycle Sort algorithm in JS

#### Languages Used:
- JavaScript

#### Files Added:
- Cycle_Sort.js

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!
@raghav-dalmia

### CODE REVIEW

**Comment by JanaSabuj** [comment]
@raghav-dalmia please do review the PR.

**Comment by jainaman224** [comment]
Please squash commits.

**Comment by jainaman224** [comment]
I like commented code. :+1:

**Comment by JanaSabuj** [comment]
@jainaman224 @asha15 @SakshiShreya I FINALLY learnt how to squash commits. SORRY for all the inconvenience. Now you can review the PR and merge it. It was a great learning process for me. Thank You.

**Pull request merged**
