### PR TITLE
Count all possible paths in mxn matrix

### LINKED ISSUE #1871: Count all possible paths in m * n matrix to move a robot from top left cell to bottom right cell in python.
`Input: m = 2, n = 3`
`Output: 3`
`Explanation: There are 3 Paths
(0 ,0)-->(0, 1)-->(0, 2)-->(1, 2)
(0 ,0)-->(0, 1)-->(1, 1)-->(1, 2)
(0 ,0)-->(1, 0)-->(1, 1)-->(1, 2)`

### PR DESCRIPTION
**Pull request by Shiv1202**
Fixes #1871

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Recursive Method for All possible paths in m*n matrix.
- 

#### Languages Used:
- Python 3
- 

#### Files Added:
-  All_possible_path_in_mxn_matrix_recursive.py
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please remove the files which is not relevant to this issue

**Comment by raghav-dalmia** [comment]
Are you working on it?

**Comment by Shiv1202** [comment]
yes sir

**Comment by somya-kapoor** [comment]
Are you working on it?

**Comment by MastersAbh** [comment]
Hi @Shiv1202 I dont see any update from your side so closing this PR.

**Pull request closed without merging**
