### PR TITLE
Dijkstra algorithm in go

### PR DESCRIPTION
**Pull request by Basilleaf24**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added Dijkstra algorithm in go #2652 
- 

#### Languages Used:
- Go
- 

#### Files Added:
- Dijkstra algorithm in go #2652
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please update PR template

**Comment by somya-kapoor** [comment]
@Basilleaf24 please update PR template

**Comment by somya-kapoor** [comment]
Are you working on it?

**Comment by somya-kapoor** [comment]
Was this issue assigned to you?

**Comment by somya-kapoor** [comment]
Don't create multiple PR for the same issue.

**Pull request closed without merging**
