### PR TITLE
Kruskal_OOP in Java

### PR DESCRIPTION
**Pull request by LauraLaureus**
Java OOP implementation of Kruskal  Issue #158

### CODE REVIEW

**Comment by jainaman224** [comment]
Can you please explain what are you working on in this PR.
I am unable to understand this. Help me please

**Comment by LauraLaureus** [comment]
I implement Kruskal algoritm using Java and Object Oriented Programming. Is it enough explanation? Tell me if you need more.

**Comment by jainaman224** [comment]
31 files for such a simple code. Actually I am unaware of idea behind this implementation. Why are you using files like .xml files.

**Comment by LauraLaureus** [comment]
Object Oriented are really bigger projects , but XML files are from Netbeans project.

**Comment by jainaman224** [comment]
Can you please make a basic program or remove unnecessary files.

**Comment by LauraLaureus** [comment]
I have just remove the Netbeans project. 
Data Structures, Data Types, Test Files and Kruskal itself remain.

**Comment by jainaman224** [comment]
Thank you
Please add README file if you can in new PR.

**Pull request merged**
