### PR TITLE
Cocktail sort Readme file

### LINKED ISSUE #997: README for Cocktail Sort
Add a README.md file to explain Cocktail Sort Algorithm. The file should contain the following:
- Explanation
- Algorithm
- Pseudocode
- Example
- Time Complexity

Also add images/GIFs to explain if possible.

### PR DESCRIPTION
**Pull request by archi14**
Fixes #997 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:

- Added Readme.md for the Cocktail Sort.

#### Languages Used:
- Markdown

#### Files Added:
- Readme file and gifs with it.

### CODE REVIEW

**Comment by somya-kapoor** [comment]
@archi14  Please fix the PR template  ( Fixes #issue number for example Fixes #2020)
and  fix the checkboxes ( [x]  not [ x]).

**Comment by archi14** [comment]
@somya-kapoor done.

**Comment by marwahmanbir** [comment]
@archi14 I see that your PR template is still not complete yet. Please complete it and then we're good to go.

**Comment by archi14** [comment]
@marwahmanbir Sorry I am a beginner. What more can I add in the PR template? I have just used pseudo code, no language and not proposing any change.

**Comment by marwahmanbir** [comment]
In the 'Language' section, mention 'Markdown'
In changes proposed, you have to mention what change/addition this PR proposes to this project.
Also complete the checklist (check the points) and remove extra bullets.

**Comment by archi14** [comment]
@marwahmanbir okay done.

**Comment by marwahmanbir** [comment]
Approved @jainaman224

**Comment by marwahmanbir** [comment]
@jainaman224 it's approved from my side, you can suggest any changes if required.

**Comment by archi14** [comment]
@GOVINDDIXIT I have made the required changes.

**Comment by jainaman224** [comment]
I think we can add image to other sources and use link here.

**Comment by archi14** [comment]
@jainaman224 I did not find any image with proper explanation that's why I created these gifs myself.

**Comment by jainaman224** [comment]
These gifs are awesome 😍 
but uploading to other sources and using their link will be great. You can use github as well.
We can discuss on slack or gitter.

**Comment by GOVINDDIXIT** [comment]
@archi14 Using links for GIF instead of storing is a better approach, Also it will help in reducing the repo size making easy to clone. Pls proceed this way

**Comment by marwahmanbir** [comment]
> @jainaman224 I did not find any image with proper explanation that's why I created these gifs myself.

Great work with the GIFs :+1:

**Comment by archi14** [comment]
@marwahmanbir  used another image now with link.

**Comment by jainaman224** [comment]
Hey,
Can you connect with me on gitter or slack?
It would be great to have those images.

**Comment by archi14** [comment]
@jainaman224 sure.

**Comment by jainaman224** [comment]
Please squash your commits and it is ready to merged.

**Comment by MastersAbh** [comment]
Hi @archi14 ,
If you are willing to move ahead with this PR and if you need assistance with squashing, you can reach out to us.

**Comment by archi14** [comment]
@MastersAbh yes sorry I don't know how to do that.

**Comment by MastersAbh** [comment]
Hi @archi14 , can we connect on Slack regarding this ?
I'd be happy to help.

**Comment by archi14** [comment]
@MastersAbh  okay.

**Pull request merged**
