### PR TITLE
C++ solution for Queens, Quick Hull, Find_Max_Subbarray, Queues_Using_Stacks, Randomized_Quick_Sort problems

### PR DESCRIPTION
**Pull request by KaysarKK**
Fixes # 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:

- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
-

### CODE REVIEW

**Comment by sridharjajoo** [comment]
Could you include the sample output as well

**Comment by jainaman224** [comment]
Please fill the PR template.
Create different PR for different issues.

**Comment by jainaman224** [comment]
@KaysarKK If you are facing any issues. You can connect with us on slack or gitter.

**Comment by jainaman224** [comment]
Hey @KaysarKK,
Do you need any assistance. Please let us know.

**Comment by MastersAbh** [comment]
You might close this due to inactivity @jainaman224

**Comment by rishabhgarg25699** [comment]
@KaysarKK @jainaman224  Closed the PR due to inactivity of the PR owner .

**Pull request closed without merging**
