### PR TITLE
EvenorOddUsingBitManip

### PR DESCRIPTION
**Pull request by AdharshM**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by MastersAbh** [comment]
Please update the checklist properly and mention which issue it is trying to fix

**Comment by SakshiShreya** [comment]
Are you working on this?

**Comment by SakshiShreya** [comment]
Are you working on this?

**Comment by MastersAbh** [comment]
@AdharshM  please let us know if you are working on this issue, else we will close the PR

**Pull request closed without merging**
