### PR TITLE
Adding PHP Implementation for Chinese Remainder Theorem (Issue #2481)

### LINKED ISSUE #2481: Chinese Remainder Theorem
- [x] C - @Anushka-Rajvanshi
- [x] C++
- [x] C#
- [x] CoffeeScript
- [x] Dart - @Rukmini-Meda
- [x] Go - @jedicakelord
- [x] Java
- [x] JS
- [ ] Kotlin
- [x] Php - @sukritishah15
- [x] Python
- [x] Readme - @chandrikadeb7
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript

### PR DESCRIPTION
**Pull request by sukritishah15**
Fixes #2481 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- PHP

#### Files Added:
- Chinese_Remainder_Theorem.php

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by sukritishah15** [comment]
@SakshiShreya @jainaman224 Kindly review my PR.

**Comment by raghav-dalmia** [comment]
squash your commits

**Comment by sukritishah15** [comment]
@raghav-dalmia Squashed commits. Kindly review.

**Comment by raghav-dalmia** [comment]
still, there are two commits. Squash them, I will merge it after that.

**Pull request closed without merging**
