### PR TITLE
Doubly_linked _list

### LINKED ISSUE #1271: Doubly Linked List implementation in ruby
@jainaman224  i would like to implement doubly linked list in ruby.

### PR DESCRIPTION
**Pull request by AnshitaVishwa**
Fixes #1271 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Implemented Doubly linked list in ruby language.

#### Languages Used:
- ruby

#### Files Added:
- Doubly_linked_list.rb

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by AnshitaVishwa** [comment]
@jainaman224  kindly review it.

**Comment by rishabhgarg25699** [comment]
@AnshitaVishwa Please try to squash your commit .

**Comment by AnshitaVishwa** [comment]
@rishabhgarg25699 i have squashed my commits.

**Comment by rishabhgarg25699** [comment]
@AnshitaVishwa I don't know ruby language . So i can not review your PR . @jainaman224 Please review it . @MastersAbh If you can please review this PR .

**Comment by AnshitaVishwa** [comment]
@MastersAbh  i have done the changes.

**Comment by AnshitaVishwa** [comment]
@marwahmanbir i have done the changes.

**Pull request merged**
