### PR TITLE
N queen using bit-masking 

### LINKED ISSUE #1597: Backtracking using Bitmasking
I would like to contribute to this problem for GSSoC'20.

### PR DESCRIPTION
**Pull request by RiaJha02**
Fixes #1597 

#### Checklist:
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] 4 space indentation.
- [x] File names are correct.
- [x] Logic Documentation (Comments).

#### Changes proposed in this pull request:
The n-queens puzzle is the problem of placing n queens on an n×n chessboard such that no two queens attack each other. This is a Backtracking based problem.
Using bitset, we will be tracking the position for the queen to be placed safely and then backtrack for other positions.

#### Languages Used:
- C++
- Java
- Python

#### Files Added:
- Backtracking_using_bitmasking.cpp
- Backtracking_using_bitmasking.java
- Backtracking_using_bitmasking.py

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
you have assigned to create Backtracking using Bitmasking but you created another thing. why is that?

**Comment by RiaJha02** [comment]
Ma'am, I have developed a bitmasking solution for a backtracking based problem. Please correct me know If something else needs to be done.

**Comment by RiaJha02** [comment]
Ma'am, I have developed a bitmasking solution for a backtracking based problem. Please correct me If something else needs to be done.

**Comment by RiaJha02** [comment]
I will link a new Pull Request for better understanding.

**Pull request closed without merging**
