### PR TITLE
#539 Added Unbounded Knapsack in C++, Java & Python

### PR DESCRIPTION
**Pull request by MastersAbh**
With respect to Issue #539

### CODE REVIEW

**Comment by jainaman224** [comment]
I have changed file name.
Please use better variable names than `f, wt, dp` etc

**Comment by MastersAbh** [comment]
Changes made @jainaman224 . Please review.

**Comment by jainaman224** [comment]
Just last thing. Please remove unused define.

**Comment by MastersAbh** [comment]
Sure, Done.

**Pull request merged**
