### PR TITLE
Floyd Warshall Algo in C #2205

### PR DESCRIPTION
**Pull request by p-soham11**
Fixes #2205 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
Adding Floyd Warshall Algorithm in C

#### Languages Used:
C

#### Files Added:
Floyd_Warshall_Algorithm.c

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by raghav-dalmia** [comment]
add issue number in the description and use [x] instead of [ *]

**Comment by raghav-dalmia** [comment]
squash your commits and remove irrelevant files.

**Comment by p-soham11** [comment]
Sir, I have done the changes with "x"

**Comment by p-soham11** [comment]
Sir, shall I need to revert this PR ? as I am unable to remove the additional file..

**Comment by somya-kapoor** [comment]
@p-soham11 Yes, if you are facing an issue in deleting the additional files, please close this PR and create a new PR.

**Comment by p-soham11** [comment]
Okay !! I will definitely do this..

**Pull request closed without merging**
