### PR TITLE
Added DSU

### PR DESCRIPTION
**Pull request by mr-pandey**
Algorithm to find all the connected components of a graph. Also used as a part of some classical algorithms such as Kruskal's Algorithm.
Shortened the code of Floyd-Warshall Algorithm

### CODE REVIEW

**Comment by jainaman224** [comment]
Please remove Floyd Warshall Code.
I don't see much optimization.

Are you particiapating in GSSoC? If yes then I will merge it on 1st March.

**Comment by jainaman224** [comment]
@mr-pandey Are you still working on it.

**Comment by mr-pandey** [comment]
> @mr-pandey Are you still working on it.

Yes I'll be back in a while

**Comment by jainaman224** [comment]
@mr-pandey What is the status?

**Comment by mr-pandey** [comment]
@jainaman224  I have already added all the stuff. This PR needs to be closed

**Pull request closed without merging**
