### PR TITLE
Quick sort in C#

### LINKED ISSUE #1629: Quick Sort implementation using C# language.
As QuickSort is not available in C#, I will like to work on it under GSSoc'20
@singh-shreya6

### PR DESCRIPTION
**Pull request by Yashank18**
Fixes #1629

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Implementation of Quick Sort 

#### Languages Used:
- C#

#### Files Added:
- Quick_sort.cs

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by Yashank18** [comment]
@singh-shreya6 Please review.

**Comment by raghav-dalmia** [comment]
squash the commits. rest looks good to me.

**Comment by Yashank18** [comment]
@raghav-dalmia  I am trying to squash these but my rebase-todo file is showing empty and I am stuck.

**Comment by Yashank18** [comment]
@SakshiShreya  @singh-shreya6, please check

**Pull request closed without merging**
