### PR TITLE
Added Hamiltonian Cycle Algorithm

### LINKED ISSUE #820: Hamiltonian Cycle
Add an algorithm to find Hamiltonian Cycle, in the following languages:
- C/C++
- Python
- Java

### PR DESCRIPTION
**Pull request by marwahmanbir**
Fixes #820 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:

- Added Hamiltonian Cycle Algorithm

#### Languages Used:
- C
- Java
- Python

#### Files Added:
- Hamiltonian_Cycle.c
- Hamiltonian_Cycle.java
- Hamiltonian_Cycle.py

### CODE REVIEW

**Comment by MastersAbh** [comment]
Hey, Your code is good and it would've been good for reviewing.
But, before that, I found it to be similar to the codes present at [https://www.geeksforgeeks.org/hamiltonian-cycle-backtracking-6/](url) . Please re-code it to avoid the similarity and then it would be reviewed. Also, use your own examples. @jainaman224

**Comment by jainaman224** [comment]
@marwahmanbir I am really disappointed to see this.

**Comment by marwahmanbir** [comment]
Hey @MastersAbh, yes, I agree that the code is similar to what you've mentioned, that's because I've referred to that one before implementing. I have tried to explain the code by adding specific comments myself. Also, the implementation of the code would remain the same, right? If you could be more specific about what to change exactly, that would be more helpful.

**Comment by jainaman224** [comment]
@marwahmanbir Actually geeks for geeks adds space after every line. General programmer never do these things. That's how we came to know. Initially, we thought it was original as well.

**Comment by marwahmanbir** [comment]
@jainaman224 Okay.. so I'll remove extra lines. Is there anything else that needs to be changed?

**Comment by jainaman224** [comment]
I am telling you. How we came to it is case of cheating.

**Comment by MastersAbh** [comment]
@marwahmanbir I agree to the fact that logic will always be the same. But, try to code it yourself. This way you have same variable names, the examples quoted is also same as in GFG. That is what plagiarism is and it is not what should be encouraged.

**Comment by marwahmanbir** [comment]
Okay, no worries. I'll code it myself and will avoid the similarity.

**Comment by MastersAbh** [comment]
Appreciate the focus. That would be great @marwahmanbir  :)

**Pull request closed without merging**
