### PR TITLE
Rabin Karp in PHP

### PR DESCRIPTION
**Pull request by coderprasukj**
Fixes #2161

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Rabin Karp Algorithm in PHP

#### Languages Used:
- PHP

#### Files Added:
- Rabin_Karp.php

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by coderprasukj** [comment]
@singh-shreya6 @somya-kapoor I have the done the required issue. Kindly have a look at it.

**Comment by asha15** [comment]
can i know the issue number?

**Comment by coderprasukj** [comment]
@asha15 The issue number is #2161. I have updated it. Please have a look at it

**Comment by coderprasukj** [comment]
@singh-shreya6 @asha15 I have squashed the commits. Please have a look at it.

**Pull request merged**
