### PR TITLE
Create arrayrotation.java

### PR DESCRIPTION
**Pull request by shortCircuit81**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by somya-kapoor** [comment]
@shortCircuit81 Please mention the issue number

**Comment by shortCircuit81** [comment]
> @shortCircuit81 Please mention the issue number

#2466

**Comment by somya-kapoor** [comment]
#2466 is the PR number, not the issue number

**Comment by asha15** [comment]
could you provide a link to your issue?

**Comment by asha15** [comment]
could you provide a link to your issue?

**Comment by raghav-dalmia** [comment]
It's more than 8 days, we didn't any response from you. I am closing this PR.

**Pull request closed without merging**
