### PR TITLE
:star: add median of two sorted arrays

### LINKED ISSUE #2018: Median of Two sorted Arrays
Median of two sorted arrays can be calculated using two pointer approach , without merging two arrays in O(n)

### PR DESCRIPTION
**Pull request by ashishnagpal2498**
Fixes #2018 

Description - The previous PR had issues due to squashing of commits.

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:
- Median of Two Sorted Arrays 
- New PR , Old closed

#### Languages Used:
- C++
-

### CODE REVIEW

**Comment by ashishnagpal2498** [comment]
@SakshiShreya @jainaman224 , Kindly review this PR.

**Comment by ashishnagpal2498** [comment]
Hi @asha15 , I am working on this. Will do the changes in few hours. Sorry for delay.

**Comment by asha15** [comment]
2 days passed :(

**Comment by ashishnagpal2498** [comment]
Hi @asha15 . Kindly review this PR. Thank you

**Comment by asha15** [comment]
please squash the commits and let me know

**Comment by ashishnagpal2498** [comment]
Done @asha15 .

**Comment by ashishnagpal2498** [comment]
Hey, could you please add an issue for this in different languages also. I would like to contribute in JS as well. Thank you :)

**Pull request merged**
