### PR TITLE
Graph Implementation in C++, Java, Python

### LINKED ISSUE #1025: Graph implementation using C++, Python
I wanted to contribute by adding simple graph implementation using C++, Python and Java for the Javascript version which exists.

### PR DESCRIPTION
**Pull request by py93**
Fixes #1025

#### Checklist:
- [X] 4 space indentation.
- [X] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [X] Sample Input / Output is added at the end of file.
- [ ] Logic Documentation (Comments).
- [X] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added Graph implementation in Java, C++, Python

#### Languages Used:
- C++
- Java
- Python

#### Files Added:
- Graph.java
- Graph.cpp
- Graph.py

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by marwahmanbir** [comment]
@py93 there seem to be multiple files in this PR, two of which do not seem to be related to the PR. Could you please remove them before this PR gets reviewed?

**Comment by py93** [comment]
@marwahmanbir The issue was to provide Java, Python and C++ implementation for Graph. Added 3 files for the corresponding implementations.

**Comment by marwahmanbir** [comment]
Looking at the "Files Changed" section of this PR, there seem to be the following two files that are not related to this PR I believe:
- Array_Rotation/ArrayRotationUsingTempArray.java (changed)
- Array_Rotation/ArrayRotationUsingTempArray.py

**Comment by py93** [comment]
@marwahmanbir Didn't notice that before. Made the modifications and updated the PR.

**Comment by rishabhgarg25699** [comment]
@py93 Please squash  your commit also .

**Comment by MastersAbh** [comment]
@marwahmanbir please have a look.

**Comment by py93** [comment]
@rishabhgarg25699 I tried to squash the commits by various different ways but keep getting that my branch is upto date and nothing to commit. What am I doing wrong? Cant see the 18 commits to pick from to squash them in git bash.

**Comment by Vaibhavpratapsingh22** [comment]
Assign me Graph code in C language.

**Pull request merged**
