### PR TITLE
Added Breadth First Search in javascript

### LINKED ISSUE #1010: breadth first search in Javascript
i am assigning this issue to myself

### PR DESCRIPTION
**Pull request by mark-nakachon**
Fixes #1010

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:

- Added Breadth first.js file 

#### Languages Used:
- Javascript

#### Files Added:
- Breadth first search.js

### CODE REVIEW

**Comment by MastersAbh** [comment]
Please use 4 spaces instead of tabs and also follow this indentation throughout the file.

**Comment by MastersAbh** [comment]
Also, fix the PR template. There are extra bullets present.

**Comment by marwahmanbir** [comment]
@mark-nakachon can you please let me know your Slack username?

**Comment by mark-nakachon** [comment]
> @mark-nakachon can you please let me know your Slack username?
Harish(P)

**Comment by marwahmanbir** [comment]
@mark-nakachon Did anyone assign you #1010? I'm not sure about other projects but here you have to get the issue assigned by the admin/mentor before you can start working on it. You can't simply assign one to yourself and start working o it straight away.
Also, I see that you're not even a member of our slack channel.
All this makes it difficult to track your contributions and you also won't know whether you're being given the points or not.

**Comment by marwahmanbir** [comment]
And I've told you many times before that a person can work on two issues at a time, that's a policy of this project.

**Comment by marwahmanbir** [comment]
And I've told you many times before that a person can work on two issues at a time, that's a policy of this project. I see that you've opened 8-10 issues at the moment!
@gupta2140 @GOVINDDIXIT

**Comment by GOVINDDIXIT** [comment]
@mark-nakachon Pls work only on those issues for which you are assigned. I can see you are already assigned for some other issues which are yet to be solved. Do not work on new issues without solving previous ones. Also as told by @marwahmanbir you can work only on 2 issues at a time.

**Comment by mark-nakachon** [comment]
@marwahmanbir does this project have slack group if yes then please send me the slack invitation link and moreover i opened these many issues because I want to engage myself in coding . At present I have my exams that's why I am not able to close all the issues  I opened 
I will soon within few days I will close all my issues and also open new one's and make this project a successful one

**Comment by marwahmanbir** [comment]
@mark-nakachon are you a GSSoC'19 participant?

**Comment by mark-nakachon** [comment]
Yes

**Comment by mark-nakachon** [comment]
Yup

**Comment by mark-nakachon** [comment]
Please merge this PR now do you find any issues now in the code please let me know

**Pull request merged**
