### PR TITLE
Added Euler's Totient Function

### PR DESCRIPTION
**Pull request by MastersAbh**
With respect to issue #646

### CODE REVIEW

**Comment by MastersAbh** [comment]
Thanks @jainaman224 . Please review.

**Comment by jainaman224** [comment]
Great work. Just squash commits now.

**Comment by MastersAbh** [comment]
Hey @jainaman224  I squashed the commits. Please review and merge.

**Comment by MastersAbh** [comment]
I am opening another PR. This got messed up.

**Pull request closed without merging**
