### PR TITLE
Added Cocktail Sort #538

### PR DESCRIPTION
**Pull request by shahkv95**
Added Python code for Cocktail Sort.
Issue: #538

### CODE REVIEW

**Comment by shahkv95** [comment]
**Removed Tower of Hanoi and renamed the file.** 
Completed the required commits. 
Please check the PR for the same.

**Comment by shahkv95** [comment]
Heyy @jainaman224 I have added the #591 issue. It contains the code for Largest Sum Contiguous Subarray in C++ and python. Please review the PR.
Thank you.

**Comment by jainaman224** [comment]
@shahkv95 Remove code for largest sum contigous subarray. Create another PR and find name for that algorithm.

**Comment by shahkv95** [comment]
Heyy @jainaman224  I have removed the Largest Sum Contiguous Array and submitting this PR for 
Cocktail_Sort/Cocktail_Sort.py.
All changes made as asked for .

**Pull request merged**
