### PR TITLE
Added implementation of algorithms 

### PR DESCRIPTION
**Pull request by hritik5102**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added a few algorithms

#### Languages Used:
- Java
- JavaScript
- C++
- C

#### Files Added:
- A star
- Bankers algorithm for deadlock avoidance
- Infix2Postfix ReadME
- Jarvis march algorithm + ReadME
- LRU algorithm
- Round robin CPU scheduling algorithm
- Computer graphics algorithm

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
@hritik5102 oh ho you have added so many changes in one commit. can i know your issue number ?

**Comment by hritik5102** [comment]
These are the algorithms that are not mentioned in the issues  .

**Comment by asha15** [comment]
@hritik5102  can i know your issue number ?

**Comment by hritik5102** [comment]
New implementation of Algorithms is added.
1. A* Star - Issue #1653 
2. Round Robin CPU Scheduling - Issue #1873 
3. Banker's Algorithm for deadlock avoidance - Issue #1893 
4. Infix to Postfix README - Issue #1897 
5. Jarvis March Algorithm ReadME - Issue 
6. LRU Algorithm - Issue #1899 
7. Computer Graphics Algorithm - Issue #1901

**Comment by Vaibhavraj10** [comment]
@hritik5102 Hey this is not the way how things work. You need to first claim an issue and then submit a PR referencing that issue. Remember you can claim at max 2 issues at a time. Make only one PR for a particular issue. I hope you understand this. Please claim the above mentioned issues and then make a PR for each issue.

**Comment by SakshiShreya** [comment]
@hritik5102  I am closing this PR. You can't raise a PR before it is allocated to you. And solve one issue in 1 PR.

**Pull request closed without merging**
