### PR TITLE
Updated Frequency_Of_A_Element.py

### PR DESCRIPTION
**Pull request by Manish-cloud**
Used inbuilt library function of list

Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Delegating responsibility to python library function (Used inbuilt library function of list).
- 

#### Languages Used:
- Python3
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by SakshiShreya** [comment]
Please complete the PR checklist properly.

**Comment by jainaman224** [comment]
No activity since 2 days.

**Comment by SakshiShreya** [comment]
@Manish-cloud are you working on it?

**Comment by somya-kapoor** [comment]
@Manish-cloud Are you working on it?

**Comment by somya-kapoor** [comment]
@Manish-cloud Due to no activities, I am closing this issue.

**Pull request closed without merging**
