### PR TITLE
Floyd warshall algorithm in C ISSUE #2205 FIXED

### PR DESCRIPTION
**Pull request by Moddy2024**
Fixes #2205 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Floyd warshall algorithm done in C 

#### Languages Used:
- C

#### Files Added:
- Floyd_Warshall_Algorithm.c

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by Moddy2024** [comment]
@asha15  @raghav-dalmia @singh-shreya6  @jainaman224  I am from GSSOC'20 please merge this on time

**Comment by somya-kapoor** [comment]
Your code is copied from geeks for geeks. Even comments are also same.

**Comment by Moddy2024** [comment]
> Your code is copied from geeks for geeks(only functions are removed). Even comments are also the same.

only the input and output were copied and the code is unique i wrote it you should have checked correctly before closing the PR

**Comment by Moddy2024** [comment]
> > Your code is copied from geeks for geeks(only functions are removed). Even comments are also the same.
> 
> only the input and output were copied and the code is unique i wrote it you should have checked correctly before closing the PR @somya-kapoor

@somya-kapoor like an idiot and a dumbass you just saw the input and closed my PR i wrote the code myself you idiot you should have checked carefully

**Comment by asha15** [comment]
Screenshot from 2020-06-01 01-22-08
Screenshot from 2020-06-01 01-22-17
Screenshot from 2020-06-01 01-22-21
Screenshot from 2020-06-01 01-22-30

@Moddy2024  Excuse me, Do you know to whom you are talking like this? your code has 60% of plagiarism. even we are closing a PR if it has 50% of plagiarism.  please learn to respect others 

@jainaman224  please block this users from the project

**Comment by Moddy2024** [comment]
> Screenshot from 2020-06-01 01-22-08
> Screenshot from 2020-06-01 01-22-17
> Screenshot from 2020-06-01 01-22-21
> Screenshot from 2020-06-01 01-22-30
> 
> @Moddy2024 Excuse me, Do you know to whom you are talking like this? your code has 62% of plagiarism. even we are closing a PR if it has 50% of plagiarism. please learn to respect others
> 
> @jainaman224 please block this users from the project

so the printf and the name of the functions and loops are same so that  means i copied it show me the code side by side from GFG that they are similar choosing i,j are common names for the loops

**Comment by asha15** [comment]
@Moddy2024  yes you can justify your fault in that way too

**Comment by Moddy2024** [comment]
@asha15  @jai you are just finding petty issues in my code everytime from the start and trying to find reasons to close my PRS no matter how much i fix it

**Comment by Moddy2024** [comment]
> because i didn't copied it 

@asha15

**Pull request closed without merging**
