### PR TITLE
update readme.md

### LINKED ISSUE #1947: priority scheduling (preemptive)  in scheduling algorithms C/C++.
I would like to work to on these algorithms in C/C++.
please assign me this issue. :)

### PR DESCRIPTION
**Pull request by pratu098**
Fixes #1947

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- C++
- 

#### Files Added:
- [Preemptive Priority.docx](https://github.com/jainaman224/Algo_Ds_Notes/files/4510018/Preemptive.Priority.docx)
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by raghav-dalmia** [comment]
Your PR dosen't have relevant files.

**Comment by somya-kapoor** [comment]
Are you working on it?

**Comment by pratu098** [comment]
Which files are you referring to?

**Comment by somya-kapoor** [comment]
Your readme file is not complete. Please see in the repository  which things to write in readme file like ago, example, pseudocode

**Comment by pratu098** [comment]
Okay

**Comment by somya-kapoor** [comment]
This is not assigned to you.

**Comment by pratu098** [comment]
I was assigned issue #1947.

**Comment by somya-kapoor** [comment]
It was for priority scheduling (preemptive) in scheduling algorithms  not for readme file

**Comment by pratu098** [comment]
Please review my PR.

**Comment by somya-kapoor** [comment]
Which PR

**Comment by pratu098** [comment]
#1947

**Comment by somya-kapoor** [comment]
This is the issue not the PR

**Comment by pratu098** [comment]
I am getting confused. Will you clear what I have to do?
Because I had been assigned issue #1947 for which I made the PR several
days ago.

**Comment by pratu098** [comment]
Sir,
My PR has all the files. If there is something I need to change please let
me know. My PR hasn't been merged and the issue is closed. It was a
confusion last time. I made PR for the issue#1947.

**Pull request closed without merging**
