### PR TITLE
Taylor series using Horner Rule using C programming language.

### LINKED ISSUE #1060: Adding Taylor series using Horner Rule in C language.
This is an algorithm of Taylor series using Horner rule, Time complexity is O(n).

### PR DESCRIPTION
**Pull request by Anshuvats**
Fixes #1060 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:

- Added Taylor series using Horner Rule using C programming language.

#### Languages Used:
- C

#### Files Added:
- Taylor_series_Using_Horner_Rule.c

### CODE REVIEW

**Comment by Anshuvats** [comment]
> Please use the template for PR description and mention issue number.

Adding Taylor series using Horner Rule in C language.

Fixes #1060(issue no.)


Changes proposed in this pull request:
Taylor series using Horner Rule using C programming language.
Languages Used:
C
Files Added:
Taylor_series_Using_Horner_Rule.c

**Comment by marwahmanbir** [comment]
@Anshuvats kindly add back the template where it was at the first place instead of a separate comment. Also, no need to describe the algorithm in the PR, you can add it in the file instead as a comment.

**Comment by Anshuvats** [comment]
ok, sir, I will do asap.

**Comment by Anshuvats** [comment]
@marwahmanbir   please review it, sir.

**Comment by marwahmanbir** [comment]
Add and complete the point that you've removed from the checklist.

**Comment by Anshuvats** [comment]
> Still the issue isn't resolved yet. There are random files by other contributors including Graham scan algorithm, Josephus algorithm, etc. Remove all the files not related to your PR.

Yes, sir! I am squashing all previous commit, I have not able to do that. How can do? , sir.

**Comment by Anshuvats** [comment]
please, sir! can you help me?

**Comment by MastersAbh** [comment]
@Anshuvats , it seems messed up, please make a new branch, pull the latest repo, add your latest codes and then open a fresh PR. It would be easier.

**Comment by Anshuvats** [comment]
@MastersAbh okay sir

**Comment by jainaman224** [comment]
@Anshuvats If you want we can fix this PR together as well.

**Pull request closed without merging**
