### PR TITLE
Adding Construction of tree given Inorder and Preorder traversal

### PR DESCRIPTION
**Pull request by isha-gautam**

### CODE REVIEW

**Comment by isha-gautam** [comment]
#513

**Comment by pankajpoply45** [comment]
I am done with the code . In which folder to add the file and then merge request? @rishabhgarg25699  @jainaman224

**Comment by pankajpoply45** [comment]
#602

**Comment by jainaman224** [comment]
Hi @pankajpoply45,
What is the issue?

**Comment by pankajpoply45** [comment]
Done with merging the code. Please review it @jainaman224

**Comment by jainaman224** [comment]
Please comment on issue instead of someone else PR.

**Pull request merged**
