### PR TITLE
Depth first search in JS. Closes #1695

### LINKED ISSUE #1695: Implement Depth_First_Search DFS in JavaScript properly.
I want to take up this implementation as part of GSSoC 20.

### PR DESCRIPTION
**Pull request by JanaSabuj**
Fixes #1695 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added DFS in JS

#### Languages Used:
- JavaScript

#### Files Added:
- Depth_First_Search.js

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by JanaSabuj** [comment]
@SakshiShreya please do review it.

**Comment by jainaman224** [comment]
Squash commits.

**Comment by jainaman224** [comment]
Using function syntax is more readable when it comes to algorithms. Arrow functions are bit confusing to me. It is just a suggestion and even I am not sure, what is better. So, it would be great if you can spare 5-10 minutes to search.

**Comment by JanaSabuj** [comment]
@jainaman224 Arrow functions are the modern syntax.
Could you please help how to squash the commits? I tried but I couldn't. Hence in another issue, I had to open a new PR. @asha15 @SakshiShreya

**Comment by JanaSabuj** [comment]
@jainaman224 @asha15 @SakshiShreya I successfully squashed the commits!!! Please merge the PR. Sorry for the inconvenience.

**Pull request merged**
