### PR TITLE
Added README.md for kadane's algorithm

### LINKED ISSUE #2247: Kadane Algorithm
- [x] C
- [x] C++
- [x] C#
- [x] CoffeeScript
- [x] Dart - @heisastark
- [x] Go - @kushagra-anand
- [x] Java
- [x] JS
- [ ] Kotlin - @yuktta
- [ ] Php - @sukritishah15
- [x] Python
- [ ] Readme - @pragyajaiswa05l
- [x] Ruby
- [ ] Rust - @ujjwaltiwari13
- [ ] TypeScript

### PR DESCRIPTION
**Pull request by pragyajaiswa05l**
Fixes #2247

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added README.md for kadane's algorithm
- 

#### Languages Used:
- 
- 

#### Files Added:
-readme.md 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by raghav-dalmia** [comment]
Complete your PR template. Also, file name should be `README.md` .

**Comment by pragyajaiswa05l** [comment]
done please review it

**Comment by pragyajaiswa05l** [comment]
@raghav-dalmia  please review it .

**Comment by asha15** [comment]
changed the file name into readme.md

**Comment by asha15** [comment]
Add more explanation

**Comment by somya-kapoor** [comment]
Due to no activity for more than a month, I am closing this PR.

**Pull request closed without merging**
