### PR TITLE
Added dynamic stack using array in c

### PR DESCRIPTION
**Pull request by vinitraj10**
#157

### CODE REVIEW

**Comment by jainaman224** [comment]
We are following gcc standard please don't include conio.h. Use online compilers like ideone for the same.
Don't take input from the user, include it yourself.
Add output at last.
Add extension for file name and change folder to include this file.
Thank you.

**Comment by vinitraj10** [comment]
okay...give me some time please!

**Comment by jainaman224** [comment]
@vinitraj10 Take your time. :smile: :+1:

**Comment by vinitraj10** [comment]
@jainaman224  i have edited where should i add the new file??

**Comment by jainaman224** [comment]
Dynamic_Stacks_Arrays and use the same file name as of java jst change the extension.

**Pull request closed without merging**
