### PR TITLE
1659

### PR DESCRIPTION
**Pull request by mehmehul**
Fixes #

#### Checklist:
- [ ] 4 space indentation.
- [ ] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [ ] Sample Input / Output is added at the end of file.
- [ ] Logic Documentation (Comments).
- [ ] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please completed the PR template 
correct the PR heading

**Comment by jainaman224** [comment]
@mehmehul Are you working on it?

**Comment by singh-shreya6** [comment]
@mehmehul The PR was not updated for over 6 days. Please let us know if you are working on it. Closing it as of now.

**Comment by mehmehul** [comment]
@singh-shreya6 can you open this again, i have will fill the checklist now, that was the only thing left

**Comment by mehmehul** [comment]
@singh-shreya6  pr for issue 1659

**Pull request closed without merging**
