### PR TITLE
Connected Components in an Undirected graph in Python3

### PR DESCRIPTION
**Pull request by prashant-mahanta**
Issue: [#740](https://github.com/jainaman224/Algo_Ds_Notes/issues/740)

### CODE REVIEW

**Comment by prashant-mahanta** [comment]
@jainaman224  Hey, in my system it is 4 spaced indentation. Here it is coming to be 8 spaces. This is what I found. Can you have a look into it: [Indent issue after commit and pushing changes to remote](https://github.com/github/VisualStudio/issues/1524)

**Comment by prashant-mahanta** [comment]
Screenshot from 2019-03-27 01-22-25

**Comment by jainaman224** [comment]
Use spaces instead of tabs.
https://stackoverflow.com/questions/14167033/visual-studio-replace-tab-with-4-spaces

**Comment by prashant-mahanta** [comment]
@jainaman224 I have fixed the issue. Thanks for the help. Have a look at it.

**Comment by jainaman224** [comment]
Good Work 👍

**Pull request merged**
