### PR TITLE
Adding new code to find all primes till a given number

### PR DESCRIPTION
**Pull request by naresh2002**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added a new code
- 

#### Languages Used:
- C++
- 

#### Files Added:
- Algo_Ds_Notes/Prime_Number/All Prime till a number N (using sieve) .cpp
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by naresh2002** [comment]
Checklist is followed.
This is my first PR. I don't know a lot about git and open source. If there is any mistake then please let me know.

**Comment by naresh2002** [comment]
@singh-shreya6 madam, you have been reviewing other PRs. If my PR is valid then please review it or if some changes are required or adding new file is not allowed then please let me know.

**Comment by somya-kapoor** [comment]
Please add issue number

**Comment by asha15** [comment]
Hi @naresh2002 

welcome to open source. TO send a PR you need to have a issue which was assigned by a mentor. If you have a issue please include it on the PR template if not please let us know

**Pull request closed without merging**
