### PR TITLE
Ford Fulkerson in C

### PR DESCRIPTION
**Pull request by MayankTripathi01**
input file attached as mf.in

### CODE REVIEW

**Comment by jainaman224** [comment]
Please don't any file for input instead add it inside code.

**Comment by MayankTripathi01** [comment]
ok now i add input inside please check ad merge it @jainaman224

**Comment by jainaman224** [comment]
remove mf.in file. using git rm file_path

**Comment by jainaman224** [comment]
Thanks for contributing.

**Pull request merged**
