### PR TITLE
Added a C++ solution to bisection method

### LINKED ISSUE #1914: Bisection method in cpp
I would like to add a solution in cpp to implement root finding method i.e The Bisection method.Please assign me this issue

### PR DESCRIPTION
**Pull request by Nikhil-Patro**
Fixes #1914

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
-Added a C++ impementation of Bisection method
#### Languages Used:
- C++
#### Files Added:
- Bisection_Method.cpp

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by Nikhil-Patro** [comment]
Please review this @jainaman224

**Comment by asha15** [comment]
please specify the issue number next to `Fixes #`

**Comment by asha15** [comment]
remove unnecessary files

**Comment by Nikhil-Patro** [comment]
I have specified the issue no.Actually, i am new to git ,so can you please tell me how to edit the unnecessary files?Do i have to close this PR and make a new one?Also,are there any other unnecessary files other than a.exe?

**Comment by asha15** [comment]
@Nikhil-Patro  It's better to close this PR and submit a new one
IF you find any difficulty reach me on slack

**Pull request closed without merging**
