### PR TITLE
Travis Based Syntex Checker

### LINKED ISSUE #597: Create Travis based syntax checker
A Travis config file has to be created with several bash files for checking syntax of the code submitted in PRs

1. A travis.yml file will be created in root. The purpose of this file would be to set up a basic Linux node on Travis and fetch all files that have been changed/created in the specific PR

2. Further, a directory "build_scripts" will be created that will contain a bash file for each language. The purpose of each file is to install the required compiler and dependencies and check syntax for a particular language

Travis CI will execute the desired file from "build_scripts" after inspecting the language of files present in the PR.

### PR DESCRIPTION
**Pull request by riya-17**
Fixes #597 

#### Checklist:
- [x] C and Python
- [ ] Different Language like C++, GO, etc
- [ ] format checking
- [ ] checking with different file names

#### Changes proposed in this pull request:
Checks for C and Python Language Files with name main.c or main.py

#### Files Added:
- .travis.yml

### CODE REVIEW

**Comment by jainaman224** [comment]
There is an issue. There is no file with main.c or main.py name.

**Comment by riya-17** [comment]
@jainaman224 try to give a pull request of C or Python file with name main.c or main.py respectively you can get the idea.

**Comment by jainaman224** [comment]
@riya-17 I do agree but modify it a fit to check for all c or python files.
Something like *.c or *.py might help.

**Comment by riya-17** [comment]
@jainaman224 ok I will find a solution for that.

**Comment by MastersAbh** [comment]
Hi @riya-17 still working on it ?

**Comment by MastersAbh** [comment]
@rishabhgarg25699 @jainaman224 you can close this PR due to inactivity.

**Comment by rishabhgarg25699** [comment]
@riya-17 @jainaman224 I am closing this issue due to inactivity of PR owner .

**Pull request closed without merging**
