### PR TITLE
Implemented queue using linked list in C

### PR DESCRIPTION
**Pull request by pranayberry**
Implemented queue using linked list in C
Ref issue #178

### CODE REVIEW

**Comment by jainaman224** [comment]
Remove file a.out.

**Comment by jainaman224** [comment]
Update Index.md.

**Comment by pranayberry** [comment]
What is index.md?

**Comment by jainaman224** [comment]
It is a file written in markdown language which serves as an Index for this repository.

**Comment by pranayberry** [comment]
So I need to add a new column for C language?

**Comment by jainaman224** [comment]
Ok leave it for now. Please remove a.out file. Thanks

**Comment by pranayberry** [comment]
Done

**Comment by pranayberry** [comment]
I have updated the Index with a new column please review it.

**Comment by ayushin78** [comment]
Thanks for the contribution.

**Comment by jainaman224** [comment]
Please resolve try to resolve conflicts and update me. Else I will try to help you. Thank you

**Comment by jainaman224** [comment]
Remove Index.md.

**Comment by pranayberry** [comment]
Done

**Pull request merged**
