### PR TITLE
Postman Sort README added 

### LINKED ISSUE #2251: Postman sort
- [ ] C - @jhasaurabh312
- [x] C++ - @coderprasukj
- [x] C#
- [ ] CoffeeScript
- [ ] Dart - @Rukmini-Meda
- [ ] Go
- [ ] Java - @bluejay229
- [x] JS - @coderprasukj
- [ ] Kotlin - @myselfanuj
- [ ] Php
- [ ] Python - @jhasaurabh312
- [x] Readme - @shwetagurnani
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript

### PR DESCRIPTION
**Pull request by shwetagurnani**
Fixes #2251 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- README added in postman sort
- 

#### Languages Used:
- 
- 

#### Files Added:
- README added
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please squash your commits and let me know

**Comment by shwetagurnani** [comment]
Thankyou ma'am for approving .I am squashing the commits

**Comment by shwetagurnani** [comment]
https://github.com/jainaman224/Algo_Ds_Notes/pull/2829

Ma'am I was facing difficulty in squashing the commit as I made the pull request using github interface and not terminal.I have made a new pull request please merge it .It has a single commit

**Comment by shwetagurnani** [comment]
Ma'am please merge it

**Comment by shwetagurnani** [comment]
Ma'am it was my first time i tried squashing the committs,first i was facing the issue as my local branch was not even with the base branch ..When i did git pull some more committs were added so while squashing by mistake i squashed some commits other than mine too .Please merge it ma'am.I'll not repeat the mistake again

**Comment by shwetagurnani** [comment]
Ma'am it was my first time i tried squashing the committs,first i was facing the issue as my local branch was not even with the base branch ..When i did git pull some more committs were added so while squashing by mistake i squashed some commits other than mine too .Please merge it ma'am.I'll not repeat the mistake again

**Comment by raghav-dalmia** [comment]
Still your PR have 2 commits.

**Pull request closed without merging**
