### PR TITLE
With refernce to #268

### PR DESCRIPTION
**Pull request by saksham0037**
```
Add code for Binary Search in C
```

### CODE REVIEW

**Comment by jainaman224** [comment]
Take an example instead of getting input from user and add output for the same.

**Comment by saksham0037** [comment]
Ok

**Comment by jainaman224** [comment]
Try to resolve conflicts

**Comment by saksham0037** [comment]
Have you already merged any code for Binary Search in C?

**Comment by jainaman224** [comment]
Unfortunately yes, sorry for that

**Pull request closed without merging**
