### PR TITLE
Rotate_linked_list_by_k_nodes

### PR DESCRIPTION
**Pull request by poorva2145**
Fixes #
new issue, new file created

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x]  Input is taken dynamically.
- [x]  Sample Input / Output is added at the end of file.
- [x]  Logic Documentation (Comments).
- [x]  File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added new file: reverse_linked_list_by_k_nodes
This code shows how to reverse a linked list by k nodes in a counter-clockwise direction.

#### Languages Used:
- c++

#### Files Added:
- reverse_linked_list_by_k_nodes.cpp

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
can i know your issue number ?

**Comment by poorva2145** [comment]
> can i know your issue number ?

Mam issue number is #2452

**Comment by asha15** [comment]
please specify it next to `Fixes #` in the PR template

**Comment by asha15** [comment]
but you was not assigned for the issue so for. 
I'm closing this PR , please send a new PR after the issue was assigned to you

**Pull request closed without merging**
