### PR TITLE
Travelling Salesman Problem using Genetic Algorithm 

### LINKED ISSUE #1975: Implementation of various Greedy and Optimal Algorithms
This repo also requires a section of greedy algorithms.

### PR DESCRIPTION
**Pull request by Ratna04priya**
Fixes #1975 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Travelling Salesman Problem usinG Genetic Algorithm  

#### Languages Used:
- Python
- Jupyter Notebook Used

#### Files Added:
- TSP_GA.ipynb
- image asserts

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by jainaman224** [comment]
Please include issue number.

**Comment by Ratna04priya** [comment]
Yeah, done with the fix.

**Comment by Ratna04priya** [comment]
Would like to know, if there is some problem in code, as it's still in review.

**Comment by asha15** [comment]
you have include a png file. please create a new PR with relevant files

**Pull request closed without merging**
