### PR TITLE
 Kadane's algortihm in c #issue:591

### PR DESCRIPTION
**Pull request by divs30**
added kaden's algortihm in c#issue:591

### CODE REVIEW

**Comment by gupta2140** [comment]
When the array is [-1,-2,-3], the minimum sum should be -1, not 0. Please correct the algorithm.

**Comment by gupta2140** [comment]
You don't need separate functions for the same purpose. Kindly research on it to understand a more intuitive way.

**Comment by divs30** [comment]
fixed file name

**Comment by jainaman224** [comment]
From next time use 4 space indentation.

**Pull request merged**
