### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by VIJAY07102**
Adding README.md for Binary Insertion sort.

### CODE REVIEW

**Comment by VIJAY07102** [comment]
@jainaman224  Review this PR, I'm adding README.md to binary insertion sort.

**Comment by asha15** [comment]
please complete the PR template

**Comment by raghav-dalmia** [comment]
Are you working on it?

**Comment by raghav-dalmia** [comment]
As I see that this is not assigned to anyone, so I am closing this PR.

**Pull request closed without merging**
