### PR TITLE
Added Prefix Sum in C++

### PR DESCRIPTION
**Pull request by mr-pandey**
Efficient algorithm to compute the sum of the elements between two given indices in O(1), i.e., constant time. The value of sum of elements from index L to R is v[R] - v[L-1] for L>0, and v[R] for L=0.

### CODE REVIEW

**Comment by jainaman224** [comment]
Please refer issue you are solving.

**Comment by mr-pandey** [comment]
Solved issue #445

**Comment by jainaman224** [comment]
> #445

It is another PR you have referred to.

**Comment by mr-pandey** [comment]
#725

**Pull request merged**
