### PR TITLE
Added pascal_triangle.py

### PR DESCRIPTION
**Pull request by aftex261**
Input:
Enter the number: 4
Output:
1
1 1
1 2 1
1 3 3 1

Fixes #2414

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- Python 
- 

#### Files Added:
- pascal_triangle.py
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by aftex261** [comment]
I have successfully completed all the steps .Please Merge it now if no bugs are present.

**Comment by asha15** [comment]
can i know your issue number?

**Comment by aftex261** [comment]
2415

**Comment by somya-kapoor** [comment]
@aftex261 There is no issue number as #2455

**Comment by aftex261** [comment]
Oh,my mistake it's 2415

**Comment by somya-kapoor** [comment]
What is the issue number which you are trying to solve?

**Comment by aftex261** [comment]
> What is the issue number which you are trying to solve?

I wasn't able to distinguish between fixed and closes .Now you can merge it.

**Comment by aftex261** [comment]
Issue number is 2414

**Comment by somya-kapoor** [comment]
Its the PR number, not the issue number

**Comment by aftex261** [comment]
> Its the PR number, not the issue number

Actually I have a bit confusion please check it for me and merge it if it is all correct.

**Comment by asha15** [comment]
sorry still i'm not getting your issue number
could you send me link for your issue?

**Comment by somya-kapoor** [comment]
@aftex261 Can't merge it until you mention the issue number. Was this issue assigned to you)

**Comment by aftex261** [comment]
No I have created this issue

**Comment by somya-kapoor** [comment]
@aftex261 Please first create an issue and when it is assigned to you, then only create the PR.

**Pull request closed without merging**
