### PR TITLE
1905

### LINKED ISSUE #1905: Binary Tree Pair Sum
Finding pairs whose sum is equal to a certain given number in Binary Tree. Implementation for this code in the missing in the project repository. I would like to work on its implementation in C++ in this issue.

### PR DESCRIPTION
**Pull request by mehmehul**
Fixes #1905, #1659

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Binary Tree Pair Sum
- Binary Tree LCA

#### Languages Used:
- C++

#### Files Added:
- Binary_Tree_Pair_Sum.cpp
- Binary_Tree_LCA.cpp

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by somya-kapoor** [comment]
Please complete the PR checklist properly.

**Comment by jainaman224** [comment]
@mehmehul Are you working on it?

**Comment by mehmehul** [comment]
Yes I'll get it done by tomorrow

**Comment by mehmehul** [comment]
@jainaman224  @somya-kapoor

**Comment by MastersAbh** [comment]
@mehmehul can you fix the checklist and mention the issue number you are working on ?

**Comment by mehmehul** [comment]
@MastersAbh  filled the checklist for both the issues. Is it fine?

**Comment by jainaman224** [comment]
Create separate PR for separate issues.

**Comment by somya-kapoor** [comment]
Please create separate PR for different issues.

**Comment by somya-kapoor** [comment]
@mehmehul Are you working on it?

**Comment by somya-kapoor** [comment]
@mehmehul Due to no activity for more than 7 days I am closing this issue.

**Pull request closed without merging**
