### PR TITLE
Some algorithms in c

### PR DESCRIPTION
**Pull request by SilentFlame**
- Circular Linked List

- Dijsktra Algorithm

- Merge Sort 
all implemented in c.

Also addresses #159

### CODE REVIEW

**Comment by jainaman224** [comment]
Take an example as input and add output for the same. Please do same to all your PR.

**Comment by SilentFlame** [comment]
For circular linked list 

here I haven't used any of the functions needed but since I have a pointer at both `head` and `tail`, it's easy to do that.
Example:
Input integers one-by-one:   `5 6 7 8 9 0 3 4`
Output: 
`
5 6 7 8 9 0 3 4
head-> 5
tail-> 4
`

**Comment by SilentFlame** [comment]
For Dijsktra Algorithm: It is implemented for `Directed Acyclic graphs`
Sample Input:
`
4 4
1 2 24
1 4 20
3 1 3
4 3 12
1
` 
Output: 
`
1 to 1 = 0
1 to 2 = 24
1 to 3 = 32
1 to 4 = 20
`

**Comment by SilentFlame** [comment]
For Merge sort:
Sample Input:
`
7

3 1 6 2 8 7 9
`
Output:
`
1 2 3 6 7 8 9
`

**Comment by SilentFlame** [comment]
@jainaman224  Is this all needed?

**Comment by jainaman224** [comment]
Yes add those example as input instead getting it from user and add output for the same.

**Comment by SilentFlame** [comment]
@jainaman224 have a look.

**Pull request merged**
