### PR TITLE
Dijkstra's algorithm in Rust

### LINKED ISSUE #2204: Dijkstra Algorithm
- [x] C
- [x] C++
- [ ] C# - @anshu18107
- [ ] CoffeeScript
- [x] Dart - @Swarnimashukla
- [ ] Go - @raksha009
- [x] Java
- [ ] JS - @abhu-A-J
- [ ] Kotlin - @garimasingh128
- [x] Php - @sukritishah15
- [x] Python
- [ ] Readme - @shwetagurnani
- [x] Ruby
- [ ] Rust - @kichloo
- [x] TypeScript

### PR DESCRIPTION
**Pull request by kichloo**
Added the program in Rust language.

Fixes #2204

#### Checklist:
- [X] 4 space indentation.
- [X] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [ ] Sample Input / Output is added at the end of file.
- [ ] Logic Documentation (Comments).
- [X] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added new file
 
#### Languages Used:
- Rust 

#### Files Added:
-  Djikstra.rs

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please include the issue number in the PR template

**Comment by kichloo** [comment]
@asha15 Done!

**Comment by asha15** [comment]
you included the PR number. can i get a link to your issue?

**Comment by kichloo** [comment]
@asha15 Pl check it, if its correct! #2204

**Comment by kichloo** [comment]
@asha15 I have given requests to work on some other issues also. As now, I have done all my issues, can I get them?

**Comment by asha15** [comment]
no you want to wait till the PR merged

please remove the irrelevant files and include the Rust file inside the respective folder

**Comment by kichloo** [comment]
@asha15 Done.

**Comment by somya-kapoor** [comment]
Are you working on it?

**Comment by kichloo** [comment]
I have submitted it for review

**Comment by MastersAbh** [comment]
Hi @kichloo I dont see any update from your side on this PR

**Pull request closed without merging**
