### PR TITLE
kruskal_Algorithm.java

### PR DESCRIPTION
**Pull request by sez98**
this is the Kruskal's algo for MST

### CODE REVIEW

**Comment by jainaman224** [comment]
Please refer the issue you are solving.

**Comment by sez98** [comment]
I am adding a .java file in the Kruskal Algorithm folder.

**Comment by sez98** [comment]
this is issue no. 158

**Comment by jainaman224** [comment]
Tag it like #158.

**Comment by jainaman224** [comment]
You have to claim issue first.
Like other people commented on it.

**Comment by sez98** [comment]
sure i ll keep that in mind from the next pull requests

**Comment by sez98** [comment]
should i create an issue and claim is first?

**Comment by jainaman224** [comment]
@sez98 Yes please create or find issue and claim it.

**Comment by jainaman224** [comment]
Issue 158 will do.

**Comment by sez98** [comment]
Changes done

**Pull request merged**
