### PR TITLE
Completed Binary Tree Right View, Bottom View and Top View in C #1577 and Linked List Merge sort #1578

### PR DESCRIPTION
**Pull request by AkanshaKamboj**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by AkanshaKamboj** [comment]
@MastersAbh I have changed the code for LinkedList and somehow Both of my pull requests are merged into one. This consists of Code for LinkedList in C,C++,Java,Python and also Bottom View, Top View, Right View of Binary tree in C language.

**Comment by AkanshaKamboj** [comment]
@raghav-dalmia Please check out this PR for Bottom View, Top View and Right View of Binary tree

**Comment by MastersAbh** [comment]
Yes @AkanshaKamboj ,
It is because you updated and pushed the code in the same branch. You need to create a different branch for creating a separate Pull Request. Please mention the issue number you are referring to

**Comment by AkanshaKamboj** [comment]
Can you please check all the codes here @MasterAbh? Otherwise it will take another 2 days for my PR to get reviewed. I have to work on different issues. So please if it is possible.

**Comment by jainaman224** [comment]
@AkanshaKamboj Please squash your commits.

**Comment by jainaman224** [comment]
Please split this PR into multiple PR to get more points. Create a PR with one of the files only.

**Comment by jainaman224** [comment]
@AkanshaKamboj Are you working on it?

**Comment by AkanshaKamboj** [comment]
Actually I am out of station and not having my laptop. But the codes are already done.

**Comment by AkanshaKamboj** [comment]
Just need to split the PR

**Pull request closed without merging**
