### PR TITLE
Implemented KNN algorithm using C++ (Closes issue #1789)

### LINKED ISSUE #1789: Add KNN Algorithm in C++
I am a GSSOC 2020 participant and I would love to implement the K Nearest Neighbors Algorithm using C++ as a part of GSSOC 2020. Please assign it to me @raghav-dalmia @asha15 @singh-shreya6

### PR DESCRIPTION
**Pull request by Aman-Codes**
Fixes #1789

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:
- Added the KNN Algorithm implemented using C++ to the Machine_Learning directory.
- Added Readme.md

#### Languages Used:
- C++

#### Files Added:
- K_Nearest_Neighbors.cpp
- Readme.md

@jainaman224 @somya-kapoor @asha15 @singh-shreya6 @raghav-dalmia

### CODE REVIEW

**Comment by Aman-Codes** [comment]
@jainaman224 @asha15 @raghav-dalmia @singh-shreya6
This pull request will close the pull request #2097

**Comment by raghav-dalmia** [comment]
We have two active PRs from you from the same issue. Close one of them.

**Comment by Aman-Codes** [comment]
@raghav-dalmia  Sir now I have closed the pull request #2097.
@somya-kapoor @jainaman224 @asha15 please review this pull request.

**Comment by Aman-Codes** [comment]
Sorry by mistake I added Tree_Inorder_Traversal.js in this branch but now it is removed.

**Pull request merged**
