### PR TITLE
1D Array in Golang

### LINKED ISSUE #2788: Implementation of 1D array programs in Go language.
I would like to contribute by creating the codes for existing 1D array programs in Go language.

**Changes proposed :**
- Add code for frequency of an element
- Max and next max number
- Mean, variance and standard deviation 
- Merge two sorted arrays

### PR DESCRIPTION
**Pull request by KamalDGRT**
Fixes #2788 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:
- Even and Odd count
- Add code for frequency of an element
- Max and next max number
- Mean, variance and standard deviation 
- Merge two sorted arrays

#### Language Used:
- Go

#### Files Added:
- EvenOdd.go
- Frequency_Of_A_Element.go
- Max_And_Next_Max_Number.go
- Mean_Variance_Standard_Deviation.go
- Merge_Two_Sorted_Arrays.go

### CODE REVIEW

**Comment by KamalDGRT** [comment]
@jainaman224 Please review these changes.

**Comment by KamalDGRT** [comment]
@MastersAbh @jainaman224 review the changes and merge them.

**Comment by MastersAbh** [comment]
Please squash your commits @KamalDGRT

**Comment by KamalDGRT** [comment]
Thank you @MastersAbh

**Comment by MastersAbh** [comment]
Please squash your commits @KamalDGRT...I will merge the PR

**Comment by KamalDGRT** [comment]
I did squash the commits. But, I do not know how the extra commit. Could you help me with how to proceed?

**Comment by KamalDGRT** [comment]
And... isn't there an option like, squash and merge?

**Comment by MastersAbh** [comment]
Please reach out to us on slack for help regarding squashing. It is for informative purpose and one should know these basic git commands, that is why we encourage squashing by participants. 
Merging it for now, but pls do reach out on slack

**Comment by MastersAbh** [comment]
Hey @KamalDGRT , I cannot proceed with the PR. I see you haven't been assigned the issue for this topic. #2788 was closed by admin, you shouldn't have raised this PR. 
Closing it. Reach out if any concern.

**Pull request closed without merging**
