### PR TITLE
Quick Sort in php

### PR DESCRIPTION
**Pull request by Neelaksh-Singh**
Fixes #

#### Checklist:
- [.] 4 space indentation.
- [.] Coding conventions are followed.
- [.] Sample Input / Output is added at the beginning of file.
- [.] Logic Documentation (Comments).
- [.] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
-Added comments 
- Proper Indentation

#### Languages Used:
- PHP

#### Files Added:
- QuickSort.php
- [QuickSortfinal.txt](https://github.com/jainaman224/Algo_Ds_Notes/files/4379141/QuickSortfinal.txt)

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please properly complete the PR template, remove irrelevant files from the branch and send a PR again

**Comment by Neelaksh-Singh** [comment]
Ma'am it doesn't takes file with .php extension

**Comment by Neelaksh-Singh** [comment]
> please properly complete the PR template, remove irrelevant files from the branch and send a PR again

Ma'am it doesn't takes file with .php extension

**Comment by asha15** [comment]
Sorry i didn't get you.


can i get a link to the issue?

**Comment by Neelaksh-Singh** [comment]
Basically it is not expecting my file in .PHP extension, thus I am
providing it in .txt file format

**Pull request closed without merging**
