### PR TITLE
Implement Armstrong in Js

### LINKED ISSUE #1861: Armstrong Number in Js
I want to add the JS implementation as part of GSSoC ' 20.
@raghav-dalmia @MastersAbh @asha15 @singh-shreya6 @SakshiShreya

### PR DESCRIPTION
**Pull request by Aju100**
Fixes #1861

#### Checklist:
- [X] 4 space indentation.
- [X] Coding conventions are followed.
- [X] Input is taken dynamically.
- [X] Sample Input / Output is added at the end of file.
- [X] Logic Documentation (Comments).
- [X] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added 

#### Languages Used:
- Js

#### Files Added:
- Armstrong_Number.c
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by raghav-dalmia** [comment]
Squash all the commits and put a small description in first line of code

**Comment by raghav-dalmia** [comment]
Also your PR show two file changes, make sure to remove linear search file.

**Comment by jainaman224** [comment]
@Aju100 Are you working on it?

**Comment by Aju100** [comment]
@jainaman224 yes

**Comment by Aju100** [comment]
@jainaman224  hello u can review , I have squash all the three commits

**Comment by Aju100** [comment]
@raghav-dalmia can u review please ?

**Comment by MastersAbh** [comment]
@Aju100 your changes still shows 2 files. Please remove linear search file from this PR

**Comment by Aju100** [comment]
@MastersAbh  sure

**Comment by jainaman224** [comment]
@Aju100 Are working on it?

**Comment by somya-kapoor** [comment]
@Aju100 Are working on it?

**Comment by somya-kapoor** [comment]
@Aju100  I am closing this PR because there is no activity for more than 7 days.

**Pull request closed without merging**
