### PR TITLE
Added Minesweeper_Game in C++

### LINKED ISSUE #1598: Minesweeper algorithm implementation in C++
I would like to make a PR on the implementation of minesweeper algorithm in C++ for GSSoC'20.

### PR DESCRIPTION
**Pull request by chandrikadeb7**
Fixes #1598 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Added Minesweeper algorithm implementation in C++
- 

#### Languages Used:
- C++
- 

#### Files Added:
- Minesweeper_Game/minesweeper.cpp
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by raghav-dalmia** [comment]
@chandrikadeb7 use 4 space indentation.

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 use 4 space indentation.

Done. Any more changes to be done?

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 use 4 space indentation.

@raghav-dalmia Done. Any more changes to do?

**Comment by raghav-dalmia** [comment]
Also squash all the commits

**Pull request closed without merging**
