### PR TITLE
1638

### PR DESCRIPTION
**Pull request by mehmehul**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please complete the PR template

**Comment by SakshiShreya** [comment]
@mehmehul are you working on it? Please write a relevant title of the PR. Also, complete the PR template properly.

**Comment by mehmehul** [comment]
@SakshiShreya  I'll complete the PR by tonight

**Comment by jainaman224** [comment]
@mehmehul Are you working on it?

**Comment by somya-kapoor** [comment]
@mehmehul Are you working on it?

**Comment by somya-kapoor** [comment]
@mehmehul I am closing this PR because there is no activity for more than 7 days.

**Comment by somya-kapoor** [comment]
@mehmehul I am closing this PR because there is no activity for more than 7 days.

**Pull request closed without merging**
