### PR TITLE
Akshay pal contibution to Matrix chain multiplication

### PR DESCRIPTION
**Pull request by Akshay2903**
Mycontribution

### CODE REVIEW

**Comment by jainaman224** [comment]
Please refer the issue you are fixing.

**Comment by Akshay2903** [comment]
Matrix chain multiplication

**Comment by jainaman224** [comment]
Remove your name from the commit message. Referring issue means `#issue_number`.

**Comment by jainaman224** [comment]
Remove your name from the commit message. Referring issue means `#issue_number`.

**Comment by jainaman224** [comment]
@Akshay2903 Are you working on it?

**Pull request closed without merging**
