### PR TITLE
quicksort_3_way done in C and C#

### PR DESCRIPTION
**Pull request by Moddy2024**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- C code for Quick Sort 3 way  implementation added
- C# code for Quick Sort 3 way  implementation added

#### Languages Used:
- C
- C#

#### Files Added:
- Quicksort_3_way.c
- Quicksort_3_way.cs

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
You didn't state the issue number, so I'm closing the PR

**Comment by Moddy2024** [comment]
> You didn't state the issue number, so I'm closing the PR

so that's the only issue right i just have to state the issue no. in topic

**Comment by Moddy2024** [comment]
> You didn't state the issue number, so I'm closing the PR

you closed each of my PR just because there wasn't a issue no. you could have just mentioned that and i could have fixed it you didn't need to close all of my PR

**Comment by asha15** [comment]
cool. If you have an assigned issue please comment the issue number, I'll reopen the PR

**Pull request closed without merging**
