### PR TITLE
Bipartite check

### PR DESCRIPTION
**Pull request by Akansha2202**
Fixes #

ISSUE NUMBER : #2317 

#### Checklist:
- [x] 4 space indentation.
- [ ] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 4 spaces
-space after , ;
-user input
-sample input

#### Languages Used:
- C++
- 

#### Files Added:
- check_graph_is_Bipartite_or_not.cpp 
- #2317 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by Akansha2202** [comment]
please review this.

**Comment by raghav-dalmia** [comment]
Add issue number in the PR template.

**Comment by asha15** [comment]
Can i get the link to your issue?

**Comment by somya-kapoor** [comment]
Are you working on it?

**Comment by MastersAbh** [comment]
I dont see any update from your side, hence closing this PR. Please reach out if you want to work on it or raise a new PR.

**Pull request closed without merging**
