### PR TITLE
Modified the Python implementation of QuickSort and wrote in easiest way

### PR DESCRIPTION
**Pull request by Priyankasaggu11929**
I have written a very easy Python implementation for QuickSort, besides, including all necessary information about the steps involved as comments.

### CODE REVIEW

**Comment by jainaman224** [comment]
Great. Can you just make partition function from this. It is easier to understand that way, as it is a divide and conquer technique. It would be great to have both of them separate.
What do you think?

**Comment by Priyankasaggu11929** [comment]
Ok @jainaman224. So, I should add the previous QuickSort implementation as well as the one I have written. Is this what you are trying to say?

**Comment by Priyankasaggu11929** [comment]
Also, can I work on updating index.md?

**Comment by jainaman224** [comment]
Please go ahead with index.md. I will update PR and ask your review.

**Comment by Priyankasaggu11929** [comment]
@jainaman224, What can I do more for this specific PR, to get it merged?

**Comment by Priyankasaggu11929** [comment]
@jainaman224, I have checked the INDEX.ms from A to K, And found the following:
1. I needed to change the cross mark to checks for various Algorithms. (For their implementation in various languages which are already there in the table.) I am done with this work.
2.  There is code implementation for some algo in languages other than stated in the Table, Should I make new columns for them and add that way?
3. Some Algo s have code implementations written in one language more than one time. Should I make a folder for them and name it by that language. So, that I can make one entry for those in the INDEX.md

**Comment by jainaman224** [comment]
Hey, I think your work on index.md is great but main concept here in quick sort was to learn divide and conquer technique. So, I think it is better to have current implementation.

**Pull request closed without merging**
