### PR TITLE
Create Prefix Sum of One Dimensional Array

### PR DESCRIPTION
**Pull request by mr-pandey**
Efficient algorithm to compute the sum of the elements between two given indices in O(1), i.e., constant time.

### CODE REVIEW

**Comment by jainaman224** [comment]
@mr-pandey Thanks for the pull request. But filename etc doesn't follow the convention.

**Comment by mr-pandey** [comment]
I cannot find any convention that needs to be followed. Can you please specify?

**Comment by jainaman224** [comment]
@mr-pandey
1. Every files goes into a folder and should contain extension.
2. If you are changing any existing code (i.e. Floyd Warshall Algorithm), please specify the specify the improvements.

Please remove (DSU) from file name. Great work

From next time try to work separate branches instead of master.
And try to make multiple PR for the different algorithms.

So, other files do not act as blocking for the mergeable work.

**Comment by jainaman224** [comment]
@mr-pandey Are you still working on it?

**Pull request closed without merging**
