### PR TITLE
Create queue.js

### PR DESCRIPTION
**Pull request by khushal87**
refer issue #553

### CODE REVIEW

**Comment by jainaman224** [comment]
I think it is Queue using linked list. Please find the relevant file in other language and fix file name.
Please add more nodes to queue and add output as comment.

**Comment by khushal87** [comment]
Could you please suggest how can i now change the file location now ??

**Comment by jainaman224** [comment]
@khushal87 Have a look at https://github.com/jainaman224/Algo_Ds_Notes/blob/master/Queue_Using_Linked_List/Queue_Linked_List.c

Do not hurry. It would be great if you take some time and submit better PR. As it will reduce your waiting time and we save review time.
I am just expecting this from you as now you have done good amount of contributions.

**Comment by khushal87** [comment]
Okay i will be patient on my approach from next time and submit a better PR

**Pull request merged**
