### PR TITLE
Added Interpolation Search

### LINKED ISSUE #1080: Interpolation Search in C and C++

### PR DESCRIPTION
**Pull request by somya-kapoor**
Fixes #1080

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:

- Added Interpolation Search in C and C++

#### Languages Used:
- C
- C++

#### Files Added:
- Interpolation_Search.c
- Interpolation_Search.cpp

### CODE REVIEW

**Comment by MastersAbh** [comment]
Some errors are not handled well in the code.
It gives me error at input:
1
5
5

**Comment by somya-kapoor** [comment]
@MastersAbh I tried but it didn't give an error.
Enter the number of elements: 3
Enter the sorted array: 1
2
2
Enter the value to be searched: 2
The element is present at index: 2

**Comment by MastersAbh** [comment]
Hey,
Try the input that I said. 
No. of elements: 1
Array : 5
Value to search: 5
The code should handle all the exceptions. 
Working on only one input cannot make the code perfect.

**Comment by somya-kapoor** [comment]
@MastersAbh Please review.

**Comment by MastersAbh** [comment]
Still error at input : 
Array size - 2
Array - [2, 2]
value to find - 2

**Comment by somya-kapoor** [comment]
@MastersAbh Please review

**Pull request merged**
