### PR TITLE
Add expression tree using array in C

### PR DESCRIPTION
**Pull request by sandhyabhan**
I want to add another code in expression tree that is using arrays in C programming language.

### CODE REVIEW

**Comment by asha15** [comment]
@sandhyabhan  your code didn't added to the PR.

-  Please make sure you have added the file in the commit 
- please mark the check list before sending a PR

if you find difficulty contact me on slack

**Comment by asha15** [comment]
@sandhyabhan can you recheck the code,it's giving some errors
also please provide the issue number you have worked and complete the checklist

**Comment by sandhyabhan** [comment]
Could u please specify what kind of error? because i tried running it and i am not getting any error.
Just to clarify I have written a code to convert a POSTFIX string(so the input must be  a postfix string)  into  an expression tree and printing it through all three traversals..postorder , inorder , prefixorder.

Thank you.

**Comment by asha15** [comment]
can you include two sample input and output in the file.then I'll start to review it

**Comment by jainaman224** [comment]
@sandhyabhan Are you working on it?

**Comment by sandhyabhan** [comment]
Yes, I am working

**Pull request closed without merging**
