### PR TITLE
PCA commit 1

### LINKED ISSUE #1583: Wish to add Python based scratch implementations of PCA, Decision Tree and KNN algorithms to Algo_Ds_Notes/Machine Learning
I wish to contribute the following:
1. Implementing Principal Component Analysis(PCA) from scratch
2. Implementing Decision Tree algorithm(finding best split based on entropy and Gini indexing) from scratch
3. Implementing K Nearest Neighbors(KNN) algorithm from scratch
I will also add proper visualization(if needed), documentation, code comments to explain logic.
Will also add README files

### PR DESCRIPTION
**Pull request by BALaka-18**
Fixes #1583 PCA part

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Implemented Principal Component Analysis from Scratch
- Added input and output at EOF.

#### Languages Used:
- Python

#### Files Added:
- pca.py

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
can i know why did you complete a part of the issue?

**Comment by BALaka-18** [comment]
> can i know why did you complete a part of the issue?

I will be adding different folders for the different algorithms. This is the PCA folder. I will push different files containing code for each algorithm. I have not completed the KNN yet. The DCT file needs changes, I am working on them.

**Comment by raghav-dalmia** [comment]
Are you working on it? I have to close this PR if your are unresponsive.

**Comment by BALaka-18** [comment]
> Are you working on it? I have to close this PR if your are unresponsive.

Yes, I am. I just started the KNN. Actuallymy exams are going on, so a bit late...sorry

**Comment by somya-kapoor** [comment]
Due to no activity for more than a month I am closing this issue.

**Pull request closed without merging**
