### PR TITLE
Quicksortreadme

### LINKED ISSUE #1479: In quick sort Readme file updation.
@jainaman224 In the quick sort example illustration we used any number as the pivot but in the code implementation we used last number as the pivot. So We should edit the Readme file and add the example with last element as the pivot.

### PR DESCRIPTION
**Pull request by lakshyajit165**
Fixes #1479

I have updated the readme as per requirement.
Please review.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
your file need more changes.
The file should contain the following:

    Explanation
    Algorithm
    Pseudocode
    Example
    Time Complexity

Also add images/GIFs to explain if possible. please do those changes

**Comment by raghav-dalmia** [comment]
Also squash all the commits before making PR.

**Comment by lakshyajit165** [comment]
@asha15  Kindly review my PR, so that I can raise other issues.

**Comment by asha15** [comment]
Still you didn't add the details i required. 
you can get a idea by referring this readme file

- https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Comb_Sort
- https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Fibonacci_Number

please improve the changes and let me know

**Comment by lakshyajit165** [comment]
@asha15 I have made the improvements as per your instructions. The readme file now contains, Explanation, Algorithm, Pseudocode, Example and Complexity(including gifs and images). Kindly review.

**Comment by asha15** [comment]
@lakshyajit165  could you please remove the unnecessary files ?

**Comment by lakshyajit165** [comment]
@asha15. Could you be a little more specific and tell me exactly which files I need to remove?

**Comment by asha15** [comment]
sure , remove  Karatsuba_Algo/explanation.md file and  Karatsuba_Algo/karatsuba.py

**Comment by asha15** [comment]
file is not available. will close this PR and create a new one

**Pull request merged**
