### PR TITLE
Pascal triangle

### PR DESCRIPTION
**Pull request by srimani-programmer**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Implementation of the Pascal Triangle in Java from Scratch

#### Languages Used:
- Java

#### Files Added:
- Pascal_Triangle.java

Problem Issue Number is: #1925
Request Issue Number is: #2166 
> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by somya-kapoor** [comment]
Please mention the issue number in your pr.
Also, In your pr, there are 4 other files are not related to this issue; please delete those files.

**Comment by srimani-programmer** [comment]
Issue number for this pull request #1925

**Comment by MastersAbh** [comment]
Please add issue number after Fixes # in the PR description

**Comment by srimani-programmer** [comment]
Issue Number for this Issue is #1925

**Comment by somya-kapoor** [comment]
@srimani-programmer  This issue is not assigned to you.

**Pull request closed without merging**
