### PR TITLE
Added pancake.js

### LINKED ISSUE #2151: Pancake Sort
- [x] C
- [x] C++
- [x] C# - @himanshusharma89
- [ ] CoffeeScript
- [ ] Dart - @Rukmini-Meda
- [x] Go - @KamalDGRT
- [ ] Java - @parjanyaacoder
- [x] JS - @sejalshri
- [ ] Kotlin - @sandhyabhan
- [ ] Php - @sakshikhachane
- [x] Python
- [ ] Readme - @Tawishi
- [x] Ruby
- [ ] Rust
- [ ] TypeScript

### PR DESCRIPTION
**Pull request by malavikasmenon**
Fixes #

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [ ] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
-  Fixed #2151 
- 

#### Languages Used:
- Javascript
- 

#### Files Added:
- pancake.js
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please complete the PR template

**Comment by somya-kapoor** [comment]
@malavikasmenon Are you working on it?

**Comment by somya-kapoor** [comment]
@malavikasmenon Are you working on it?

**Comment by malavikasmenon** [comment]
Yes I am

**Comment by AdityaShD** [comment]
please complete as soon as possible

**Comment by malavikasmenon** [comment]
I had edited the PR template and submitted

**Comment by MastersAbh** [comment]
@malavikasmenon are you still working on this ?

**Comment by somya-kapoor** [comment]
Due to no activity for more than 7 days, I am closing this issue.

**Pull request closed without merging**
