### PR TITLE
Shortest Path between two cells in a Matrix using BFS

### LINKED ISSUE #798: BFS on a matrix in C++, Java and Python
Computing Shortest path between two cells in a matrix

### PR DESCRIPTION
**Pull request by singh-shreya6**
Fixes #798 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [x] Sample Input / Output.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

#### Changes proposed in this pull request:
-  Added Implementation for finding shortest path between source and destination cells in a Matrix using BFS

#### Languages Used:
- C++
- Java
- Python

#### Files Added:
- BFS_On_Matrix.cpp
- BFS_On_Matrix.java
- BFS_On_Matrix.py

### CODE REVIEW

**Comment by jainaman224** [comment]
I think maxtrix shortest path is bit confusing as there are many algorithms to do so.

**Comment by singh-shreya6** [comment]
> I think maxtrix shortest path is bit confusing as there are many algorithms to do so.

what about BFS on Matrix?

**Comment by jainaman224** [comment]
Go ahead.

**Comment by singh-shreya6** [comment]
Closing this PR and opening a fresh PR due to errors in syncing.

**Pull request closed without merging**
