### PR TITLE
Added Sum_Of_Digits.js Closes #1610

### LINKED ISSUE #1610: Sum of Digits in JS.
I would like to implement this problem in JavaScript. (GSSoc20)

### PR DESCRIPTION
**Pull request by JanaSabuj**
Fixes #1610 

#### Checklist:
- [x] 4 space indentation.
- [x] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [x] Sample Input / Output is added at the end of file.
- [x] Logic Documentation (Comments).
- [x] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- Implemented Sum_Of_Digits in JS

#### Languages Used:
- JavaScript

#### Files Added:
- Sum_Of_Digits.js

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by JanaSabuj** [comment]
@asha15 @SakshiShreya the approved changes are in this new PR. please do review.

**Comment by asha15** [comment]
why did you create a new PR?

**Comment by JanaSabuj** [comment]
@asha15 I was unable to squash the commits. I tried but I couldn't.

**Comment by JanaSabuj** [comment]
@asha15 I learnt to squash commits finally. I am closing this unwanted PR. Pleas revert back to the old one. #1724

**Pull request closed without merging**
