### PR TITLE
Diagonal diff

### PR DESCRIPTION
**Pull request by p-bucky**
Fixes #

#### Checklist:
- [X] 4 space indentation.
- [X] Coding conventions are followed.
- [X] Input is taken dynamically.
- [X] Sample Input / Output is added at the end of file.
- [X] Logic Documentation (Comments).
- [X] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
I've written code for Diagonal Difference in Java.

#### Languages Used:
Java 

#### Files Added:
Diagonal_Difference.java

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

### CODE REVIEW

**Comment by asha15** [comment]
please specify the issue number next to `Fixes #`

**Comment by SakshiShreya** [comment]
@p-bucky are you working on it?

**Comment by MastersAbh** [comment]
@p-bucky Please confirm if you are working on this or we'll close the issue.

**Comment by SakshiShreya** [comment]
Since no one is working on this, I am closing this PR.
@p-bucky

**Pull request closed without merging**
