### PR TITLE
Fixes #202

### LINKED ISSUE #202: Documentation
Add documentation to the folders where there is no README.md file.

### PR DESCRIPTION
**Pull request by nitishkd**
Added README.md in each folder.

### CODE REVIEW

**Comment by jainaman224** [comment]
I can't get you, what you trying to do. Please explain

**Comment by nitishkd** [comment]
Basically i copied the README.md file to all the folders and then push the code. I wonder if this one was required.

**Comment by jainaman224** [comment]
@nitishkd No, actually we want README.md file specifically for that folder explaining the algorithm/data structure of that folder.

**Comment by nitishkd** [comment]
I can help with the algorithms I know.

**Pull request closed without merging**
